#!/bin/bash

set -e

repos_all=()
repos_loose=()
repos_dirty=()

while IFS= read -r -d '' gitconfig; do
	repo=$(dirname "$(dirname "${gitconfig}")")

	if [[ ! $(cd "${repo}" && git remote 2>/dev/null) ]]; then
		repos_loose+=("${repo}")
	elif [[ $(cd "${repo}" && git status --porcelain) ]]; then
		repos_dirty+=("${repo}")
	fi

	repos_all+=("${repo}")
done < <(find . -type f -path '*/.git/config' -print0 | sort -z)

function use_colors() {
	case "${TERM}" in
	xterm-color | *-256color) return 0 ;;
	esac

	if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
		return 0
	fi

	echo return 1
}

red=''
reset=''

if use_colors; then
	red='\e[0;31m'
	reset='\e[0m'
fi

echo -e "Found ${#repos_all[@]} repositories\n"

if [ ${#repos_dirty[@]} -gt 0 ]; then
		echo "Dirty repositories:"
		echo -e '  (use "cd <dir> && git commit" to commit changes)\n'
		printf "\t${red}%s${reset}\n" "${repos_dirty[@]}"
		echo
fi

if [ ${#repos_loose[@]} -gt 0 ]; then
		echo "Loose repositories:"
		echo -e '  (use "cd <dir> && git remote add origin <url>" to add remote repository)\n'
		printf "\t${red}%s${reset}\n" "${repos_loose[@]}"
		echo
fi